- hosts: all
  tasks:
    - name: Copy the artifact
      copy:
        src: app
        dest: /home/laborant/app

    - name: Create a unit file
      become: True
      copy:
        src: app.service
        dest: 
          /etc/systemd/system/app.service

    - name: Start the service
      become: True
      ansible.builtin.systemd:
        name: app.service
        daemon_reload: true
        state: started
