apiVersion: v1
kind: Service
metadata:
  label:
    app: myapp
  name: myapp-deployment
spec:
  ports:
   port: 4444
  - protocol: TCP
    targetPort:Â 4444
  selector:
    app: mypp
  type: ClusterIP
  
