# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build My Go App

on:
  push:
    branches: [ "*" ]
  
jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'
    - name: Test
      run: go test -v ./...
      
    - name: Build
      run: go build app.go

    - name: Deploy
      run: 
        echo "${{ secrets.MYKEY }}" > ~/.ssh/mykey
        chmod 600 ~/.ssh/mykey
        scp -o StrictHostKeyChecking=no -i ~/.ssh/mykey app laborant@target:~/
        scp -o StrictHostKeyChecking=no -i ~/.ssh/mykey myapp.service laborant@target:~/
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/mykey laborant@target "chmod +x app"
        ssh -o StrictHostKeyChecking=no -i ${FILENAME} ${USERNAME}@target "sudo systemctl start app" || true

        
        
